def problem_2():
#Each new term in the Fibonacci sequence is generated by adding the previous two
# terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed
#four million, find the sum of the even-valued terms.

# 1. establish fibonacci algorithm
# 2. run through addition
    i = 1
    n = 1
    total = 0
    #build Fibonacci
    while i <= 4000000:
        # test for even values and total
        if i % 2 == 0:
        #aggregate
            total = total + i
    # Fibonacci incrementation
        i,n = n, i+n
        # (1,1) = (1,1+1)
        # (1,2) = (2,2+1)
        # (2,3) = (3,3+2)
    print total
problem_2()
